### ISSUE TITLE
Summon thing!

### ISSUE THREAD

**Issue by Celtic7** [PCasafont/L2T_Server#6]
Hello, i got something strange.

The Summons not react for a few action. Example

Human Wizard / Kat the Cat

- Change movement mode (strange). That Cat don't want to come back.
(I think is not just that Cat) Tested: Elf / Boxer Pony and  Human / Mew the Cat --> Have same problem.

- Master recharge (strange). Looks "Master Recharge" function not working. (Same problem with the Pony)

But the Pet is working just tested "Wolf". He come back when i press "Change Movement Mode".

Just let you know: )

Thanks

**Comment by PCasafont** [comment]
I know, wont fix

**Comment by Celtic7** [comment]
Cause the "Change Movement Mode" already done. If you interested.

**Comment by PCasafont** [comment]
issue a pull request

**Comment by Celtic7** [comment]
Okay, sent it. I think i did it good, cause this was my first pull request.
