### ISSUE TITLE
not be able to connect to the server

### ISSUE THREAD

**Issue by fmpoffice** [PCasafont/L2T_Server#8]
The server set up open success, but not be able to connect to the server, enter the password after account has remained in the interface of validation.

![1](https://cloud.githubusercontent.com/assets/11001031/20292768/43fb642a-ab2b-11e6-93b2-0a3ccefe8880.png)

C:\L2Tenkai_Server\login\config\local.properties

`GameserverHostname=183.60.201.217
GameserverHosts=183.60.201.217,127.0.0.1
GameserverSubnets=0.0.0.0/0,127.0.0.0/8
GameserverPort=7777
LoginPort=9014
GameDbURL=jdbc:mysql://localhost/l2jdb
GameDbLogin=root
GameDbPassword=*******
LoginHost=183.60.201.217
LoginserverHostname=183.60.201.217
LoginserverPort=2106
LoginHostname=183.60.201.217
ListenLoginPort=9014
LoginDbURL=jdbc:mysql://localhost/l2jdb
LoginDbLogin=root
LoginDbPassword=*******
AutoCreateAccounts=true
IsUnderground=true
ServerListType=0x80`

**client for 64 EP3_0: Helios**

![2](https://cloud.githubusercontent.com/assets/11001031/20292790/6af513fa-ab2b-11e6-9ec2-b4072abeed16.png)

**The IP address has been modified connection**

![3](https://cloud.githubusercontent.com/assets/11001031/20292820/a1194618-ab2b-11e6-8496-6489e57bcc4b.png)

**Enter the password account, unable to connect, the server nor any hint!**
![4](https://cloud.githubusercontent.com/assets/11001031/20292867/23fa9be0-ab2c-11e6-8180-2f7cbd039dd7.png)

**Comment by PCasafont** [comment]
This is not a support service lol

**Comment by fmpoffice** [comment]
What should I do

**Comment by fmpoffice** [comment]
How to enter the game？can you help me
